[build]
  publish = "static"
  functions = "netlify/functions"

[functions.server]
  included_files = ["templates/**", "app.py", "data.json"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
